-- MySQL Script generated by MySQL Workbench
-- 05/22/15 00:41:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema turingca
-- -----------------------------------------------------
-- 图灵社团数据库
DROP SCHEMA IF EXISTS `turingca` ;

-- -----------------------------------------------------
-- Schema turingca
--
-- 图灵社团数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `turingca` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `turingca` ;

-- -----------------------------------------------------
-- Table `turingca`.`tca_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turingca`.`tca_user` ;

CREATE TABLE IF NOT EXISTS `turingca`.`tca_user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键自增',
  `account` CHAR(20) NOT NULL DEFAULT '' COMMENT '账号(学号)',
  `password` CHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
  `registime` INT(10) UNSIGNED NOT NULL COMMENT '注册时间,非负时间戳',
  `lock` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否锁定 0否1是',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `account` (`account` ASC))
ENGINE = MyISAM
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `turingca`.`tca_userinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turingca`.`tca_userinfo` ;

CREATE TABLE IF NOT EXISTS `turingca`.`tca_userinfo` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `nickname` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '昵称',
  `truename` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '真实姓名',
  `sex` ENUM('男', '女') NOT NULL DEFAULT '男' COMMENT '性别',
  `location` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '籍贯',
  `constellation` CHAR(10) NOT NULL DEFAULT '' COMMENT '星座',
  `intro` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '一句话简介',
  `avatar50` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '50*50头像',
  `avatar80` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '80*80头像',
  `avatar180` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '180*180头像',
  `style` VARCHAR(45) NOT NULL DEFAULT 'default' COMMENT '个人主页模板',
  `follow` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '关注数',
  `fans` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '粉丝数',
  `weibo` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '微博数',
  `uid` INT NOT NULL COMMENT '所属用户id',
  PRIMARY KEY (`id`),
  INDEX `uid` (`uid` ASC))
ENGINE = MyISAM
COMMENT = '用户信息表';


-- -----------------------------------------------------
-- Table `turingca`.`tca_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turingca`.`tca_group` ;

CREATE TABLE IF NOT EXISTS `turingca`.`tca_group` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(45) NOT NULL COMMENT '分组名称',
  `uid` INT NOT NULL COMMENT '所属用户id',
  PRIMARY KEY (`id`),
  INDEX `uid` (`uid` ASC))
ENGINE = MyISAM
COMMENT = '用户关注分组表';


-- -----------------------------------------------------
-- Table `turingca`.`tca_follow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turingca`.`tca_follow` ;

CREATE TABLE IF NOT EXISTS `turingca`.`tca_follow` (
  `follow` INT UNSIGNED NOT NULL COMMENT '我关注用户的id',
  `fans` INT UNSIGNED NOT NULL COMMENT '关注我的用户id',
  `gid` INT NOT NULL COMMENT '所属关注分组id',
  INDEX `follow` (`follow` ASC),
  INDEX `fans` (`fans` ASC),
  INDEX `gid` (`gid` ASC))
ENGINE = MyISAM
COMMENT = '用户关注与粉丝表';


-- -----------------------------------------------------
-- Table `turingca`.`tca_letter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turingca`.`tca_letter` ;

CREATE TABLE IF NOT EXISTS `turingca`.`tca_letter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `from` INT NOT NULL COMMENT '发信用户',
  `content` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '私信内容',
  `time` INT(10) UNSIGNED NOT NULL COMMENT '发信时间',
  `uid` INT NOT NULL COMMENT '所属用户id（收信人）',
  PRIMARY KEY (`id`),
  INDEX `uid` (`uid` ASC))
ENGINE = MyISAM
COMMENT = '私信表';


-- -----------------------------------------------------
-- Table `turingca`.`tca_weibo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turingca`.`tca_weibo` ;

CREATE TABLE IF NOT EXISTS `turingca`.`tca_weibo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '微博内容',
  `isturn` INT NOT NULL DEFAULT 0 COMMENT '是否转发 0否 如果是则保存该转发微博的id',
  `time` INT(10) UNSIGNED NOT NULL COMMENT '微博发布时间',
  `turn` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '转发数',
  `keep` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '收藏数量',
  `comment` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论数量',
  `uid` INT NOT NULL COMMENT '所属用户id',
  PRIMARY KEY (`id`),
  INDEX `uid` (`uid` ASC))
ENGINE = MyISAM
COMMENT = '微博表';


-- -----------------------------------------------------
-- Table `turingca`.`tca_picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turingca`.`tca_picture` ;

CREATE TABLE IF NOT EXISTS `turingca`.`tca_picture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mini` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '小图',
  `medium` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '中图',
  `max` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '大图',
  `wid` INT NOT NULL COMMENT '所属微博id',
  PRIMARY KEY (`id`),
  INDEX `wid` (`wid` ASC))
ENGINE = MyISAM
COMMENT = '微博配图表';


-- -----------------------------------------------------
-- Table `turingca`.`tca_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turingca`.`tca_comment` ;

CREATE TABLE IF NOT EXISTS `turingca`.`tca_comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '评论内容',
  `time` INT(10) UNSIGNED NOT NULL COMMENT '评论时间',
  `uid` INT NOT NULL COMMENT '评论用户id',
  `wid` INT NOT NULL COMMENT '所属微博id',
  PRIMARY KEY (`id`),
  INDEX `uid` (`uid` ASC),
  INDEX `wid` (`wid` ASC))
ENGINE = MyISAM
COMMENT = '微博评论表';


-- -----------------------------------------------------
-- Table `turingca`.`tca_keep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turingca`.`tca_keep` ;

CREATE TABLE IF NOT EXISTS `turingca`.`tca_keep` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NOT NULL COMMENT '收藏用户的id',
  `time` INT(10) UNSIGNED NOT NULL COMMENT '收藏时间',
  `wid` INT NOT NULL COMMENT '所属微博id',
  PRIMARY KEY (`id`),
  INDEX `wid` (`wid` ASC),
  INDEX `uid` (`uid` ASC))
ENGINE = MyISAM
COMMENT = '微博收藏表';


-- -----------------------------------------------------
-- Table `turingca`.`tca_atme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turingca`.`tca_atme` ;

CREATE TABLE IF NOT EXISTS `turingca`.`tca_atme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wid` INT NOT NULL COMMENT '提到我的微博id',
  `uid` INT NOT NULL COMMENT '所属用户id',
  PRIMARY KEY (`id`),
  INDEX `uid` (`uid` ASC),
  INDEX `wid` (`wid` ASC))
ENGINE = MyISAM
COMMENT = '艾特我的';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
